### ISSUE TITLE
open position

### ISSUE THREAD

**Issue by Pandena** [imhunterand/TRIGCS2#1]
Hello, are you still an active developer in cs? We would like to hire you to work on a p2p skin trading system for our platform

**Comment by imhunterand** [comment]
**Hi!** Good Morning, @Pandena 

If you have feedback of any kind regarding Counter-Strike 2, whether it's an idea, a feature request, or something that was in Counter-Strike 2 , please send an email to the CS2 team using the email address: cs2team@valvesoftware.com or personal email imhunterand@cyberservices.com
